#!/bin/sh

die()
{
  echo "ERROR: $*" 1>&2
  exit 1
}

if [ ! -d "/boot/EFI/BOOT" ]; then
  echo "You need to mount /boot first."
  exit -1
fi

echo "downloading ... 'bootx64.efi'"
# TODO: use default repo if /etc/zep/repo doesn't exist
wget $(cat /etc/zep/repo)/bootx64.efi -O /boot/EFI/BOOT/bootx64.efi || die "Could not download 'bootx64.efi'" # TODO: save to tmp, only move if download successful
echo "... done"

